const express=require("express"),path=require("path"),crypto=require("crypto"),sqlite3=require("sqlite3").verbose();
const app=express(),PORT=process.env.PORT||3000,ADMIN_EMAIL=process.env.ADMIN_EMAIL||"admin@example.com",ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"ChangeMe123!";
const db=new sqlite3.Database(process.env.DB_FILE||"./earn.sqlite"); const sessions=new Map();
app.use(express.json()); app.use(express.static(path.join(__dirname,"public")));
db.serialize(()=>{db.run(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,email TEXT UNIQUE,password_hash TEXT,balance REAL DEFAULT 0,referral_code TEXT UNIQUE,created_at TEXT)`);
db.run(`CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,title TEXT,reward REAL,description TEXT,active INTEGER DEFAULT 1)`);
db.run(`CREATE TABLE IF NOT EXISTS completed_tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,task_id TEXT,day TEXT,UNIQUE(user_id,task_id,day))`);
db.run(`CREATE TABLE IF NOT EXISTS withdrawals(id TEXT PRIMARY KEY,user_id TEXT,amount REAL,method TEXT,payment_id TEXT,status TEXT DEFAULT 'pending',created_at TEXT)`);
db.run(`CREATE TABLE IF NOT EXISTS ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,type TEXT,amount REAL,note TEXT,created_at TEXT)`);
const s=db.prepare("INSERT OR IGNORE INTO tasks VALUES(?,?,?,?,1)");[
["daily-checkin","Daily Check-in",5,"Check in once every day."],
["watch-promotion","Watch Promotion",10,"Complete the promotion task."],
["community-join","Community Join",15,"Join the community."],
["daily-task","Daily Task",5,"Complete the daily task."]
].forEach(x=>s.run(x));s.finalize();});
const hash=x=>crypto.createHash("sha256").update(x).digest("hex"), tok=()=>crypto.randomBytes(32).toString("hex");
function auth(req,res,next){const u=sessions.get(req.headers.authorization?.replace("Bearer ",""));if(!u)return res.status(401).json({error:"Login required"});req.user=u;next()}
function admin(req,res,next){if(req.headers["x-admin-key"]!==hash(ADMIN_EMAIL+":"+ADMIN_PASSWORD))return res.status(403).json({error:"Admin access denied"});next()}
app.post("/api/register",(q,r)=>{let {name,email,password}=q.body;if(!name||!email||!password||password.length<6)return r.status(400).json({error:"Fill all fields; password must be 6+ characters."});let id=crypto.randomUUID(),code="REF"+crypto.randomBytes(4).toString("hex").toUpperCase();db.run("INSERT INTO users VALUES(?,?,?,?,?,?,?,?)",[id,name.trim(),email.toLowerCase().trim(),hash(password),0,code,new Date().toISOString()],function(e){if(e)return r.status(409).json({error:"Email already registered."});let t=tok();sessions.set(t,{id,name:name.trim(),email:email.toLowerCase().trim()});r.json({token:t,name:name.trim(),balance:0,referralCode:code})})});
app.post("/api/login",(q,r)=>{let email=String(q.body.email||"").toLowerCase().trim();db.get("SELECT * FROM users WHERE email=?",[email],(e,u)=>{if(e||!u||u.password_hash!==hash(q.body.password||""))return r.status(401).json({error:"Invalid email or password."});let t=tok();sessions.set(t,{id:u.id,name:u.name,email:u.email});r.json({token:t,name:u.name,balance:u.balance,referralCode:u.referral_code})})});
app.get("/api/me",auth,(q,r)=>db.get("SELECT id,name,email,balance,referral_code FROM users WHERE id=?",[q.user.id],(e,u)=>e||!u?r.status(404).json({error:"User not found"}):r.json(u)));
app.get("/api/tasks",auth,(q,r)=>db.all("SELECT id,title,reward,description FROM tasks WHERE active=1",(e,x)=>r.json(x||[])));
app.post("/api/tasks/:id/complete",auth,(q,r)=>{let day=new Date().toISOString().slice(0,10);db.get("SELECT * FROM tasks WHERE id=? AND active=1",[q.params.id],(e,t)=>{if(!t)return r.status(404).json({error:"Task not found"});db.run("INSERT INTO completed_tasks(user_id,task_id,day) VALUES(?,?,?)",[q.user.id,t.id,day],function(er){if(er)return r.status(409).json({error:"Already completed today."});db.run("UPDATE users SET balance=balance+? WHERE id=?",[t.reward,q.user.id],()=>{db.run("INSERT INTO ledger(user_id,type,amount,note,created_at) VALUES(?,?,?,?,?)",[q.user.id,"credit",t.reward,t.title,new Date().toISOString()]);db.get("SELECT balance FROM users WHERE id=?",[q.user.id],(_,u)=>r.json({balance:u.balance,reward:t.reward}))})})})});
app.get("/api/history",auth,(q,r)=>db.all("SELECT type,amount,note,created_at FROM ledger WHERE user_id=? ORDER BY id DESC LIMIT 50",[q.user.id],(e,x)=>r.json(x||[])));
app.post("/api/withdraw",auth,(q,r)=>{let amount=Number(q.body.amount),method=q.body.method,paymentId=String(q.body.paymentId||"").trim();if(!amount||amount<=0||!method||!paymentId)return r.status(400).json({error:"Complete all withdrawal details."});db.get("SELECT balance FROM users WHERE id=?",[q.user.id],(e,u)=>{if(!u||amount>u.balance)return r.status(400).json({error:"Insufficient balance."});let id=crypto.randomUUID();db.run("UPDATE users SET balance=balance-? WHERE id=?",[amount,q.user.id],()=>{db.run("INSERT INTO withdrawals VALUES(?,?,?,?,?,?,?)",[id,q.user.id,amount,method,paymentId,"pending",new Date().toISOString()],()=>{db.run("INSERT INTO ledger(user_id,type,amount,note,created_at) VALUES(?,?,?,?,?)",[q.user.id,"debit",amount,"Withdrawal request",new Date().toISOString()]);r.json({balance:u.balance-amount,status:"pending"})})})})});
app.post("/api/admin/login",(q,r)=>q.body.email===ADMIN_EMAIL&&q.body.password===ADMIN_PASSWORD?r.json({adminKey:hash(ADMIN_EMAIL+":"+ADMIN_PASSWORD)}):r.status(401).json({error:"Invalid admin credentials"}));
app.get("/api/admin/stats",admin,(q,r)=>{db.get("SELECT COUNT(*) c FROM users",(e,a)=>db.get("SELECT COALESCE(SUM(balance),0) b FROM users",(e,b)=>db.get("SELECT COUNT(*) c FROM withdrawals WHERE status='pending'",(e,c)=>db.get("SELECT COALESCE(SUM(amount),0) a FROM withdrawals WHERE status='pending'",(e,d)=>r.json({users:a.c,balance:b.b,pending:c.c,pendingAmount:d.a}))))))});
app.get("/api/admin/users",admin,(q,r)=>db.all("SELECT id,name,email,balance,referral_code,created_at FROM users ORDER BY created_at DESC",(e,x)=>r.json(x||[])));
app.get("/api/admin/withdrawals",admin,(q,r)=>db.all("SELECT w.*,u.name,u.email FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.created_at DESC",(e,x)=>r.json(x||[])));
app.post("/api/admin/withdrawals/:id",admin,(q,r)=>{let status=q.body.status;if(!["approved","rejected"].includes(status))return r.status(400).json({error:"Invalid status"});db.get("SELECT * FROM withdrawals WHERE id=?",[q.params.id],(e,w)=>{if(!w||w.status!=="pending")return r.status(400).json({error:"Not pending"});if(status==="rejected")db.run("UPDATE users SET balance=balance+? WHERE id=?",[w.amount,w.user_id],()=>finish());else finish();function finish(){db.run("UPDATE withdrawals SET status=? WHERE id=?",[status,w.id],()=>r.json({ok:true}))}})});
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));app.listen(PORT,()=>console.log("http://localhost:"+PORT));
